package coordinator

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/hex"
	"fmt"
	"math/big"
	"net"
	"time"
)

// Identity is the set of credentials generated by "coordinator init": a
// cluster ID, a join token that authorizes worker enrollment, and a TLS
// identity the coordinator presents on its enrollment endpoint. Nothing in
// this package persists an Identity to disk; the caller decides what, if
// anything, to do with the returned value.
type Identity struct {
	ClusterID string
	JoinToken string

	TLSCert tls.Certificate

	// Fingerprint is the hex-encoded SHA-256 digest of the leaf
	// certificate's raw DER bytes. Workers pin their TLS trust to this
	// value instead of relying on a certificate authority.
	Fingerprint string
}

// NewIdentity generates a brand new cluster ID, join token, and
// self-signed TLS identity.
func NewIdentity() (*Identity, error) {
	clusterID, err := newToken("cluster", 8)
	if err != nil {
		return nil, fmt.Errorf("coordinator: generate cluster id: %w", err)
	}
	joinToken, err := newToken("join", 32)
	if err != nil {
		return nil, fmt.Errorf("coordinator: generate join token: %w", err)
	}
	cert, err := generateSelfSignedCert()
	if err != nil {
		return nil, fmt.Errorf("coordinator: generate TLS identity: %w", err)
	}
	return newIdentityFromCert(clusterID, joinToken, cert)
}

// NewIdentityFromCert builds an Identity from a caller-supplied cluster ID,
// join token, and TLS certificate (for example one loaded from disk by the
// caller). This package still does not read or write that certificate
// itself.
func NewIdentityFromCert(clusterID, joinToken string, cert tls.Certificate) (*Identity, error) {
	if clusterID == "" {
		return nil, fmt.Errorf("coordinator: cluster id must not be empty")
	}
	if joinToken == "" {
		return nil, fmt.Errorf("coordinator: join token must not be empty")
	}
	return newIdentityFromCert(clusterID, joinToken, cert)
}

func newIdentityFromCert(clusterID, joinToken string, cert tls.Certificate) (*Identity, error) {
	if len(cert.Certificate) == 0 {
		return nil, fmt.Errorf("coordinator: TLS certificate has no leaf")
	}
	leaf, err := x509.ParseCertificate(cert.Certificate[0])
	if err != nil {
		return nil, fmt.Errorf("coordinator: parse leaf certificate: %w", err)
	}
	sum := sha256.Sum256(leaf.Raw)
	return &Identity{
		ClusterID:   clusterID,
		JoinToken:   joinToken,
		TLSCert:     cert,
		Fingerprint: hex.EncodeToString(sum[:]),
	}, nil
}

// newToken returns a random hex token prefixed with label, e.g.
// "cluster_9f3a...".
func newToken(label string, nBytes int) (string, error) {
	b := make([]byte, nBytes)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return label + "_" + hex.EncodeToString(b), nil
}

func generateSelfSignedCert() (tls.Certificate, error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return tls.Certificate{}, fmt.Errorf("generate key: %w", err)
	}

	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return tls.Certificate{}, fmt.Errorf("generate serial: %w", err)
	}

	now := time.Now()
	template := &x509.Certificate{
		SerialNumber: serial,
		Subject:      pkix.Name{CommonName: "distributed-monero-coordinator"},
		DNSNames:     []string{"distributed-monero-coordinator"},
		IPAddresses:  []net.IP{net.IPv4(127, 0, 0, 1), net.IPv6loopback},
		NotBefore:    now.Add(-5 * time.Minute),
		NotAfter:     now.Add(365 * 24 * time.Hour),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}

	der, err := x509.CreateCertificate(rand.Reader, template, template, &key.PublicKey, key)
	if err != nil {
		return tls.Certificate{}, fmt.Errorf("create certificate: %w", err)
	}

	return tls.Certificate{
		Certificate: [][]byte{der},
		PrivateKey:  key,
	}, nil
}
